import React from 'react';

import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

import { Header } from '@/app/ui/Header';
import { Footer } from '@/app/ui/Footer';

import './globals.css';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} min-h-[480px] h-screen overflow-hidden flex flex-col justify-between`}>
        <Header />
        <div className={'overflow-auto w-full h-full'}>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
